# Generated by Django 5.2.5 on 2025-08-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_finepayment_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finepayment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='finepayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
